# Generated by Django 2.1.7 on 2020-08-10 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_followrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrelation',
            name='following',
        ),
        migrations.AddField(
            model_name='followrelation',
            name='following',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
