# Generated by Django 2.1.7 on 2020-08-10 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20200810_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrelation',
            name='following',
        ),
        migrations.AddField(
            model_name='followrelation',
            name='following',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
