# Generated by Django 2.1.7 on 2020-08-11 10:36

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200810_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookingFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookingfor', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_as',
            new_name='im',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Country',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='about',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='categories',
            field=models.CharField(choices=[('Business Advisor', 'Business Advisor'), ('Financial Advisor', 'Financial Advisor'), ('Technical Advisor', 'Technical Advisor'), ('Legal Advisor', 'Legal Advisor'), ('Chater Accountant', 'Chater Accountant'), ('Company secretary', 'Company secretary'), ('Content Writter', 'Content Writter'), ('Graphic Designer', 'Graphic Designer'), ('Adv. Film Maker', 'Adv. Film Maker'), ('Web Developer', 'Web Developer'), ('Software Developer', 'Software Developer'), ('App Developer', 'App Developer'), ('Digital Marketing', 'Digital Marketing'), ('Event Planner', 'Event Planner'), ('Data Entry Operator', 'Data Entry Operator'), ('Telecaller', 'Telecaller'), ('Markeitng', 'Markeitng'), ('Hr', 'Hr')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lookingfor',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lookingfor',
            field=models.ManyToManyField(to='users.LookingFor'),
        ),
    ]
