# Generated by Django 2.1.7 on 2020-07-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofndprofile',
            name='skills',
            field=models.ManyToManyField(to='forms.SKILLS'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='reqskills',
            field=models.ManyToManyField(to='forms.SKILLS'),
        ),
    ]
