# Generated by Django 2.1.7 on 2020-07-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20200713_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workprofile',
            name='jobapplication',
            field=models.IntegerField(default=0),
        ),
    ]
