# Generated by Django 2.1.7 on 2020-07-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20200713_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='jobtilte',
        ),
        migrations.DeleteModel(
            name='WorkProfile',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
