# Generated by Django 2.1.7 on 2020-07-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20200714_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='looking_for',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cofndprofile',
            name='yourself',
            field=models.CharField(choices=[('student', 'student'), ('enterpreneur', 'enterpreneur'), ('Businessman', 'Businessman'), ('Employee', 'Employee')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.CharField(choices=[('student', 'student'), ('enterpreneur', 'enterpreneur'), ('Businessman', 'Businessman'), ('Employee', 'Employee')], max_length=100),
        ),
    ]
