# Generated by Django 2.1.7 on 2020-07-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20200714_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='looking_for',
            new_name='lookingfor',
        ),
    ]
