# Generated by Django 2.1.7 on 2020-07-19 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20200714_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='Company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Companyprofile', to='forms.CompanyBase'),
        ),
    ]
