# Generated by Django 2.1.7 on 2020-07-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_auto_20200719_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='Company',
        ),
        migrations.AddField(
            model_name='companybase',
            name='About_cmp',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='companybase',
            name='Businesstype',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companybase',
            name='City',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companybase',
            name='cmp_address',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companybase',
            name='industry',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
    ]
