# Generated by Django 2.1.7 on 2020-08-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_subcategories_forcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancersprofile',
            name='workas',
        ),
        migrations.DeleteModel(
            name='Subcategories',
        ),
    ]
