# Generated by Django 2.1.7 on 2020-08-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_auto_20200808_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
