# Generated by Django 2.1.7 on 2020-08-10 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_auto_20200810_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cofndprofile',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='cofndprofile',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='cofndprofile',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='cofndprofile',
            name='passing_year',
        ),
        migrations.RemoveField(
            model_name='edudetails',
            name='user',
        ),
        migrations.AddField(
            model_name='cofndprofile',
            name='education',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Cofounder_edu', to='forms.EduDetails'),
            preserve_default=False,
        ),
    ]
