# Generated by Django 2.1.7 on 2020-08-10 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_auto_20200810_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edudetails',
            name='name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Edu_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
