# Generated by Django 2.1.7 on 2020-08-11 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0020_auto_20200810_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='CofounderExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post', models.CharField(max_length=300)),
                ('starting_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField()),
                ('ex_company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cofounder_experience_company', to='forms.CompanyBase')),
            ],
        ),
        migrations.CreateModel(
            name='CofounderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im', models.CharField(choices=[('student', 'student'), ('enterpreneur', 'enterpreneur'), ('Businessman', 'Businessman'), ('Investor', 'Investor'), ('Freelancers', 'Freelancers'), ('Student Enterpreneur', 'Student Enterpreneur')], max_length=100)),
                ('looking_for', models.CharField(choices=[('startup-idea', 'startup-idea'), ('startup-company', 'startup-company')], max_length=100)),
                ('industry', models.CharField(max_length=200)),
                ('join_startup_as', models.CharField(choices=[('cofounder', 'cofounder'), ('team-member', 'team-member'), ('partner', 'partner'), ('others', 'others')], max_length=100)),
                ('workat', models.CharField(blank=True, max_length=200)),
                ('aboutyourself', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('education', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cofounder_edu', to='forms.EduDetails')),
                ('skills', models.ManyToManyField(to='forms.SKILLS')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Cofounder_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cofndprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='cofndprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='cofndprofile',
            name='user',
        ),
        migrations.RenameField(
            model_name='jobopening',
            old_name='ForCompany',
            new_name='job_companyname',
        ),
        migrations.RenameField(
            model_name='jobopening',
            old_name='JobTilte',
            new_name='jobtilte',
        ),
        migrations.RenameField(
            model_name='jobopening',
            old_name='JobType',
            new_name='jobtype',
        ),
        migrations.RenameField(
            model_name='jobopening',
            old_name='Last_date',
            new_name='last_date',
        ),
        migrations.RenameField(
            model_name='jobopening',
            old_name='Location',
            new_name='location',
        ),
        migrations.AddField(
            model_name='jobopening',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobopening',
            name='qualification',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='experience',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.DeleteModel(
            name='CofndProfile',
        ),
        migrations.AddField(
            model_name='cofounderexperience',
            name='forcofoubnder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cofounder_profile', to='forms.CofounderProfile'),
        ),
    ]
