# Generated by Django 2.1.7 on 2020-08-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_auto_20200811_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cofounderexperience',
            old_name='forcofoubnder',
            new_name='forcofounder',
        ),
    ]
