# Generated by Django 2.1.7 on 2020-08-12 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0023_auto_20200811_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchisee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='logo_pics')),
                ('im', models.CharField(choices=[('Franchisee', 'Franchisee'), ('Distributor', 'Distributor'), ('Wholesaler', 'Wholesaler')], max_length=100)),
                ('bussiness_email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('bussiness_address', models.TextField(max_length=300)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('industry_type', models.CharField(max_length=100)),
                ('companyyouworkfor', models.CharField(blank=True, max_length=100)),
                ('about', models.TextField()),
                ('experience', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comapny_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchisee_company', to='forms.CompanyBase')),
            ],
        ),
        migrations.CreateModel(
            name='Franchisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providing', models.CharField(max_length=100)),
                ('brand_fee', models.CharField(blank=True, max_length=10)),
                ('investment_req', models.CharField(blank=True, max_length=100)),
                ('space_req', models.CharField(blank=True, max_length=100)),
                ('staff_no', models.CharField(blank=True, max_length=10)),
                ('monthly_sale', models.CharField(max_length=50)),
                ('profit', models.CharField(blank=True, max_length=50)),
                ('royalties', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchisor_company', to='forms.CompanyBase')),
                ('product_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchisor_products', to='forms.Products')),
            ],
        ),
        migrations.CreateModel(
            name='FundingPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookingfor', models.CharField(max_length=200)),
                ('funding_required', models.CharField(blank=True, max_length=10)),
                ('comapany_stage', models.CharField(choices=[('Startup', 'Startup'), ('MNC', 'MNC'), ('Experianced', 'Experianced')], max_length=100)),
                ('year_of_establish', models.DateField()),
                ('employee_No', models.CharField(max_length=5)),
                ('business_type', models.CharField(max_length=100)),
                ('business_description', models.CharField(max_length=100)),
                ('highlights', models.CharField(blank=True, max_length=200)),
                ('annual_turnover', models.CharField(blank=True, max_length=10)),
                ('growth_rate', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company_funding', to='forms.CompanyBase')),
            ],
        ),
        migrations.CreateModel(
            name='LookingForFranchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment', models.CharField(blank=True, max_length=100)),
                ('space', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('product_or_services', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('industry_type', models.CharField(max_length=100)),
                ('business_nature', models.CharField(max_length=100)),
                ('about_comapny', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='jobopening',
            name='job_description',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='im',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Employee', 'Employee'), ('Job Seeker', 'Job Seeker')], max_length=100),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='im',
            field=models.CharField(choices=[('Individual Investor', 'Individual Investor'), ('Angel Investor', 'Angel Investor'), ('Venture Capitalist', 'Venture Capitalist'), ('Investor Group', 'Investor Group')], max_length=100),
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
        migrations.AddField(
            model_name='franchisee',
            name='lookingforfranchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchisee_lookingfor', to='forms.LookingForFranchise'),
        ),
        migrations.AddField(
            model_name='franchisee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Franchisee_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
