# Generated by Django 2.1.7 on 2020-08-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0024_auto_20200813_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cofounderexperience',
            name='forcofounder',
        ),
        migrations.AddField(
            model_name='cofounderprofile',
            name='experience',
            field=models.ManyToManyField(to='forms.CofounderExperience'),
        ),
    ]
