# Generated by Django 2.1.7 on 2020-08-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0025_auto_20200814_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cofounderprofile',
            name='experience',
            field=models.ManyToManyField(blank=True, to='forms.CofounderExperience'),
        ),
    ]
