# Generated by Django 2.1.7 on 2020-08-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0026_auto_20200814_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internprofile',
            name='experience',
        ),
        migrations.AddField(
            model_name='internprofile',
            name='experience',
            field=models.ManyToManyField(blank=True, to='forms.CofounderExperience'),
        ),
    ]
