# Generated by Django 2.1.7 on 2021-01-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0027_auto_20200819_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
